
spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret



server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080  # 서버 포트 설정
  serverAddress: localhost


serverName: local_server
---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080  # 서버 포트 설정
  serverAddress: 3.37.250.123


serverName: blue_server
---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081  # 서버 포트 설정
  serverAddress: 3.37.250.123


serverName: green_server
---

spring:
  config:
    activate:
      on-profile: local


  datasource:
#    url: jdbc:h2:mem:testdb  # 인메모리 DB 사용
    url: jdbc:h2:mem:testdb;MODE=MySQL # MySQL 호환 모드 사용
#    url: jdbc:h2:file:./data/db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE # MySQL 호환 모드 사용
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 경로 (기본: /h2-console)

  jpa:
    hibernate:
      ddl-auto: update  # 애플리케이션 시작 시 테이블 자동 생성
    show-sql: true  # SQL 쿼리 출력

logging:
  level:
    root: INFO
    woongjin.gatherMind: DEBUG